### ISSUE TITLE
Can't build due to environment variable

### ISSUE THREAD

**Issue by JsonLinesCode** [shakebugs/shake-flutter#1]
I have tried to build the demo app but my android build can't succeed as `android/build.gradle:43` contains an env variable.

**Comment by mstanic-shake** [comment]
Hi, sorry for the late answer. We'll check this and then get back to you soon.

**Comment by mstanic-shake** [comment]
Hi @JsonLinesCode there is a .run folder which contains configurations you can use in Android Studio to run the project.
These configurations are using simple scripts under example/.scripts folder to run the app and set env variables.

**Comment by JsonLinesCode** [comment]
It makes sense ! Good luck on future updates.
