### ISSUE TITLE
Execution failed for task ':shake_flutter:compileDebugKotlin'

### ISSUE THREAD

**Issue by FabianVarela** [shakebugs/shake-flutter#3]
Hi, **_shakebugs_** team.

Currently, I'm using the latest version of the `shake_flutter` package (`16.2.1`). However, I must update my **Android** project, including the Java version, to `17` because most dependencies must be updated in the pubspec file. The problem is that I get an error when I update. This is the error below:

![Screenshot 2024-04-01 at 1 32 15 PM](https://github.com/shakebugs/shake-flutter/assets/8941029/ee0f101a-cb24-4999-9ff3-56b9f1c5f8aa)

Have you thought of updating the version to support Java 17?

Thanks for the package's support 👍

**Comment by FabianVarela** [comment]
To continue this issue, I have made a fork to update the Java version to 17. Also, I set the dependencies values for **Android** and **iOS** to get the dependencies because I don't get the environment variables.

This is the [fork link](https://github.com/FabianVarela/shake-flutter) if anybody also needs it.

**Comment by mstanic-shake** [comment]
Thanks @FabianVarela , we'll definitely check this and your forked repo and probably include code in a new version.

**Comment by FabianVarela** [comment]
Thanks @mstanic-shake
