### ISSUE TITLE
Namespace missing in modules build file

### ISSUE THREAD

**Issue by SahanMonaara** [shakebugs/shake-flutter#5]
I found this issue on 16.2.1. I think there is a missing namespace on AndroidManifest.xml file. 
Could you please look into this issue. Thanks!

<img width="1371" alt="Screenshot 2024-05-22 at 09 04 44" src="https://github.com/shakebugs/shake-flutter/assets/23328262/dc678d9d-9685-491b-a679-16c742d33b49">

**Comment by mstanic-shake** [comment]
Hi @SahanMonaara, thanks for a report. We'll check this and update as soon as possible.

**Comment by SahanMonaara** [comment]
Thanks @mstanic-shake , waiting for your update.

**Comment by SahanMonaara** [comment]
@mstanic-shake found the issue. It was on my end. minSdkversion was 21 on my project, while it should have been 24.
