### ISSUE TITLE
System language is ignored

### ISSUE THREAD

**Issue by sinelser** [shakebugs/shake-flutter#7]
Hello, first of all, thank you for the great product 👍 

I have a problem with displaying SDK in another language. I tried to change the iPhone language settings to Spanish and Czech, but still, after shaking I see UI in English.

I use the version 17.0.1

**Comment by sinelser** [comment]
In the bug report I see my locale as "en-CZ"

**Comment by mstanic-shake** [comment]
@sinelser For ios, you should enable mentioned languages in Xcode before building the app. For Android it should work out of the box.
Please check if this is the case.

**Comment by sinelser** [comment]
Resolved, thanks!
